spring:
  application:
    name: eventpaigergateway
  cloud:
    gateway:
      routes:
        - id: eventpaigerusers
          uri: http://localhost:31002
          predicates:
            - Path=/eventpaigerusers/api/auth/**,/api/v1/**
        - id: eventpaigerevents
          uri: http://localhost:32002
          predicates:
            - Path=/eventpaigerevents/api/v1/**
