server:
  port: 8222

spring:
  application:
    name: eventpaigergateway
  cloud:
    gateway:
      routes:
        - id: eventpaigerusers
          uri: http://event-paiger-users:31002
          predicates:
            - Path=/eventpaigerusers/api/auth/**,/api/v1/**
        - id: eventpaigerevents
          uri: http://event-paiger-events:32002
          predicates:
            - Path=/eventpaigerevents/api/v1/events/**


