server:
  port: 8222

spring:
  application:
    name: eventpaigergateway
  cloud:
    gateway:
      routes:
        - id: eventpaigerusers
          uri: http://event-paiger-users:31002
          predicates:
            - Path=/api/auth/**
        - id: eventpaigerevents
          uri: http://event-container-events:32002
          predicates:
            - Path=/api/v1/events/**
