spring:
  application:
    name: eventpaigergateway
  cloud:
    gateway:
      routes:
        - id: eventpaigerusers
          uri: http://localhost:31002
          predicates:
            - Path=/api/auth/**
        - id: eventpaigerevents
          uri: http://localhost:32002
          predicates:
            - Path=/api/v1/events/**
